### ISSUE TITLE
Review quality of video/mov file in readme

### ISSUE THREAD

**Issue by Rainiefantasy** [aim-rsf/cprd-data-wrangle#10]
**I would like to see this change implemented:**

- See if there is a way to improve the quality of the video/.mov file in the readme documentation

**Additional context or further questions:**

- RS had a look previously but couldn't find anything; GH requires downsizing video which lowers the quality

**Comment by RayStick** [comment]
**Related issue:** normally if I reload the page the video on the README appears. Now it is not working ('No video with supported format and MIME type found') - do you get the same error?

**Comment by Rainiefantasy** [comment]
Fixed :) will close
